/**
 * Generates signing keys and secrets. Prints .env-style lines to stdout only.
 * Never writes files.
 *
 * Usage: npm run secrets:generate
 */
import { randomBytes, randomUUID } from 'node:crypto';

import { exportJWK, generateKeyPair } from 'jose';

import { TOKEN_ALG } from '../packages/protocol/src/index.ts';

function toSingleLineJson(value: unknown): string {
  return JSON.stringify(value);
}

async function main(): Promise<void> {
  const { privateKey, publicKey } = await generateKeyPair(TOKEN_ALG, {
    extractable: true,
  });

  const privateJwk = await exportJWK(privateKey);
  const publicJwk = await exportJWK(publicKey);
  const sessionSecret = randomBytes(32).toString('base64url');
  const robotId = randomUUID();

  const privateLine = toSingleLineJson(privateJwk);
  const publicLine = toSingleLineJson(publicJwk);

  console.log('# Generated by npm run secrets:generate');
  console.log('# Paste each line into the file named in the comment above it.');
  console.log('# WARNING: Never commit these values. Never paste the private key');
  console.log('# or SESSION_SECRET anywhere except Vercel / web/.env.local.');
  console.log('');
  console.log('# --- web/.env.local (and Vercel project env) ---');
  console.log(`SESSION_SECRET=${sessionSecret}`);
  console.log(`TOKEN_SIGNING_PRIVATE_JWK=${privateLine}`);
  console.log('');
  console.log('# --- robot/.env (and /etc/teleop/robot.env on the Pi) ---');
  console.log(`TOKEN_PUBLIC_JWK=${publicLine}`);
  console.log(`ROBOT_ID=${robotId}`);
  console.log('');
  console.log(
    '# Also put this same ROBOT_ID into ROBOTS_JSON on the web side as "id".',
  );
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`secrets:generate failed: ${message}`);
  process.exitCode = 1;
});
